json.id event.id
json.title event.title
json.description event.description
json.start_at event.start_at
json.end_at event.end_at
json.attendees event.attendees
json.address event.address
json.latitude event.latitude
json.longitude event.longitude
